// Cards
export const CARD_FLEETS_REQUESTS = 4;
export const CARD_ACCOUNTS_BALANCE = 7;
export const CARD_CLEARANCES_REQUEST = 6;

// Labels
export const LABEL_ACCOUNTS_BALANCE = "TRESORERIE NET";
export const LABEL_FLEETS_REQUESTS = "DEMANDES DE FLOTTES";
export const LABEL_CLEARANCES_REQUEST = "DEMANDES DE DESTOCKAGES";
