// Cards
export const CARD_FLEETS_REQUESTS_MTN = 0;
export const CARD_FLEETS_REQUESTS_YUP = 4;
export const CARD_CLEARANCES_REQUEST_MTN = 1;
export const CARD_FLEETS_REQUESTS_ORANGE = 2;
export const CARD_CLEARANCES_REQUEST_YUP = 5;
export const CARD_FLEETS_REQUESTS_YOOMEE = 6;
export const CARD_CLEARANCES_REQUEST_ORANGE = 3;
export const CARD_CLEARANCES_REQUEST_YOOMEE = 7;

// Labels
export const LABEL_FLEETS_REQUESTS_YUP = "DEMANDES DE FLOTTES YUP";
export const LABEL_FLEETS_REQUESTS_MTN = "DEMANDES DE FLOTTES MTN";
export const LABEL_FLEETS_REQUESTS_ORANGE = "DEMANDES DE FLOTTES ORANGE";
export const LABEL_FLEETS_REQUESTS_YOOMEE = "DEMANDES DE FLOTTES YOOMEE";
export const LABEL_CLEARANCES_REQUEST_MTN = "DEMANDES DE DESTOCKAGES MTN";
export const LABEL_CLEARANCES_REQUEST_YUP = "DEMANDES DE DESTOCKAGES YUP";
export const LABEL_CLEARANCES_REQUEST_ORANGE = "DEMANDES DE DESTOCKAGES ORANGE";
export const LABEL_CLEARANCES_REQUEST_YOOMEE = "DEMANDES DE DESTOCKAGES YOOMEE";
