// Cards
export const CARD_FLEETS_REQUESTS_MTN = 0;
export const CARD_CLEARANCES_REQUEST_MTN = 1;
export const CARD_FLEETS_REQUESTS_ORANGE = 2;
export const CARD_CLEARANCES_REQUEST_ORANGE = 3;

// Labels
export const LABEL_FLEETS_REQUESTS_MTN = "DEMANDES DE FLOTTES MTN";
export const LABEL_FLEETS_REQUESTS_ORANGE = "DEMANDES DE FLOTTES ORANGE";
export const LABEL_CLEARANCES_REQUEST_MTN = "DEMANDES DE DESTOCKAGES MTN";
export const LABEL_CLEARANCES_REQUEST_ORANGE = "DEMANDES DE DESTOCKAGES ORANGE";
